fix: Use alias schema
snapshot-labs/snapshot-sequencer pull request #192
Opened 2023-10-05 06:47 UTC by ChaituVR

Merge after updating snapshot.js version https://github.com/snapshot-labs/snapshot.js/pull/913

2023-10-05 15:24 UTC, wa0x6e commented on src/writer/alias.ts
> +    return Promise.reject('wrong statement format');
```suggestion
    return Promise.reject('wrong alias format');
```

2023-10-05 15:25 UTC, wa0x6e requested changes

2023-10-05 15:25 UTC, wa0x6e commented on src/writer/alias.ts
> +    log.warn(`[writer] Wrong statement format ${JSON.stringify(schemaIsValid)}`);
```suggestion
    log.warn(`[writer] Wrong alias format ${JSON.stringify(schemaIsValid)}`);
```

2023-10-05 15:42 UTC, wa0x6e requested changes
`verify` expect a Promise.rejection on error

2023-10-05 15:42 UTC, wa0x6e commented on src/writer/alias.ts
> +  return message.from !== msg.payload.alias;
```suggestion
  if (message.from === msg.payload.alias) {
    return Promise.reject('alias cannot be the same as the address');
  }
```

2023-10-05 15:43 UTC, wa0x6e commented
I've also commit some tests

2023-10-06 07:01 UTC, ChaituVR commented on src/writer/alias.ts
> +  return message.from !== msg.payload.alias;
```suggestion
  if (message.from === msg.payload.alias) {
	    return Promise.reject('alias cannot be the same as the address');
	}
  return true;
```

2023-10-06 07:14 UTC, wa0x6e commented
Lint error coming from suggested changes 🙈

2023-10-06 14:16 UTC, wa0x6e approved these changes
tAck

2023-10-07 08:55 UTC, merged