fix: Change length of address fields
snapshot-labs/snapshot-sequencer pull request #396
Opened 2024-06-29 06:45 UTC by ChaituVR

Same as https://github.com/snapshot-labs/snapshot-hub/pull/877

2024-06-29 21:18 UTC, wa0x6e requested changes

2024-06-29 21:18 UTC, wa0x6e commented on test/schema.sql
>    space VARCHAR(64) NOT NULL,
`space` is also 100 on this votes table

2024-06-30 02:02 UTC, ChaituVR commented on test/schema.sql
>    space VARCHAR(64) NOT NULL,
```suggestion
  space VARCHAR(100) NOT NULL,
```

2024-06-30 02:03 UTC, wa0x6e approved these changes
utAck

2024-06-30 02:06 UTC, merged