feat: accept longer app property
snapshot-labs/snapshot-sequencer pull request #463
Opened 2024-10-17 12:32 UTC by wa0x6e

2024-10-17 15:56 UTC, ChaituVR requested changes

2024-10-17 15:56 UTC, ChaituVR commented on src/helpers/utils.ts
> +  if (!app || app?.length > 128) return '';
We should update on snapshot.js instead

https://github.com/snapshot-labs/snapshot.js/blob/master/src/schemas/proposal.json#L86

2024-10-17 16:38 UTC, ChaituVR approved these changes
utAck

2024-10-17 20:40 UTC, wa0x6e commented
PR reverted to original 24 chars limit for `app`.

Will update the limit again when database will be updated

2024-12-06 15:36 UTC, bonustrack approved these changes

2024-12-07 02:42 UTC, merged

2024-12-07 15:23 UTC, ChaituVR commented
Need to revert on snapshot.js as well?

2024-12-08 06:10 UTC, wa0x6e commented
> Need to revert on snapshot.js as well?

Correct, see https://github.com/snapshot-labs/snapshot.js/pull/1098