fix: add new columns in schema.sq
snapshot-labs/snapshot-sequencer pull request #469
Opened 2024-11-04 05:03 UTC by wa0x6e

2024-11-30 11:33 UTC, wa0x6e commented
Any updates on this one ? All tests are failing

2024-11-30 13:43 UTC, ChaituVR commented
As far as I remember @bonustrack asked us to wait, but I'm not sure exactly. Do you think we can proceed? @bonustrack

2024-11-30 18:33 UTC, bonustrack commented
I've changed the new types on the `proposals` table to be:
<img width="791" alt="image" src="https://github.com/user-attachments/assets/00f58d28-59a0-42fe-8a54-67d3234bfdef">
If you can update it, then all good for me. Later I'll also add some types on the `votes` table

2024-12-01 02:59 UTC, wa0x6e commented
Updated

2024-12-02 12:18 UTC, ChaituVR commented on test/schema.sql
> +  id VARCHAR(66) NOT NULL DEFAULT '',
Don't think we should have default values, specially with `id` we always want it to be random
any reason to add default values?

also not sure we want to update our prod DB with these 🙈  better to change schema of new values only? 😅

2024-12-02 12:20 UTC, ChaituVR commented on test/schema.sql
> +  cb INT NOT NULL DEFAULT 0,
No cb on We should add same on https://github.com/snapshot-labs/snapshot-hub/blob/master/src/helpers/schema.sql 🤔 new field?

2024-12-02 12:53 UTC, ChaituVR commented on test/schema.sql
> +  id VARCHAR(66) NOT NULL DEFAULT '',
hmmm correct 😢 werid, i don't understand why we need a default, maybe production has a outdated schema 🥲

2024-12-05 15:46 UTC, ChaituVR commented on test/schema.sql
> +  id VARCHAR(66) NOT NULL DEFAULT '',
which way we go?

2025-01-07 05:32 UTC, ChaituVR requested changes
We

2025-01-07 05:32 UTC, ChaituVR commented on test/schema.sql
We should keep it the same as hub's schema.sql to avoid confusion, we should change it there along with this

2025-01-07 05:32 UTC, ChaituVR commented on test/schema.sql
> +  id VARCHAR(66) NOT NULL DEFAULT '',
I don't think `id` should have a default value, because this should be unique, and we can't update prod DB now to remove default (it may take lot of time). maybe we can just remove this default?

2025-01-07 05:32 UTC, ChaituVR commented on test/schema.sql
> +  ipfs VARCHAR(64) NOT NULL DEFAULT '',
default here also doesn't make sense we always need an IPFS

2025-01-07 07:55 UTC, wa0x6e commented on test/schema.sql
Will open a PR on the hub with the same changes once this PR is approved

2025-01-07 08:50 UTC, ChaituVR commented on test/schema.sql
> +  scores_total_value DECIMAL(64,30) NOT NULL DEFAULT '0.000000000000000000000000000000',
I feel like this default size can increase our DB size no?

2025-01-07 09:36 UTC, merged