fix: update privacy check logic in proposal
snapshot-labs/snapshot-sequencer pull request #475
Opened 2024-12-05 15:17 UTC by ChaituVR

Discussion https://github.com/snapshot-labs/sx-monorepo/pull/954#discussion_r1867920957

### Summary

- Modifies privacy check to throw error only if user try to pass `privacy` in proposal and `space` is not using any `privacy`

### How to test

- Use UI of https://github.com/snapshot-labs/sx-monorepo/pull/954
- Try changing settings to `shutter`
- Try creating a proposal 
- Proposal should go in without any error (also with old UI)

2024-12-08 05:34 UTC, wa0x6e requested changes
Added some tests, and seems like 2 scenarios are failing

2025-01-04 09:56 UTC, ChaituVR commented
Fixed tests

2025-01-06 18:07 UTC, wa0x6e commented on test/unit/writer/proposal.test.ts
> +        it('accepts a proposal with empty string in privacy', async () => {
This test is nested inside `'when the space is using SHUTTER privacy'`, and should accept only `shutter` as value, and not `""`

2025-01-07 05:33 UTC, ChaituVR commented on test/schema.sql
> +  vp_value_by_strategy JSON DEFAULT NULL,
```suggestion
```

2025-01-07 05:45 UTC, ChaituVR commented
Tests failing are not related to this PR, we can proceed without it

2025-01-07 09:44 UTC, wa0x6e commented on test/unit/writer/proposal.test.ts
> +        it('accepts a proposal with empty string in privacy', async () => {
The test above is for another scenario.

This current test is for when the space has set `SHUTTER` as privacy, and we're sending an empty string as proposal privacy.

In this case, the writer should reject, since empty string (== no privacy), and we can not disable privacy is space has enforced it.

2025-01-07 09:45 UTC, wa0x6e commented on src/writer/update-proposal.ts
> +    msg.payload.privacy &&
This check will ignore empty string, and is the reason why one of the original test is failing

2025-01-07 18:28 UTC, wa0x6e approved these changes
tAck

2025-01-07 18:46 UTC, merged